# Generated by Django 4.2.14 on 2025-10-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_address_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', '-id'], 'verbose_name_plural': 'Addresses'},
        ),
    ]
