--
-- PostgreSQL database dump
--

\restrict lprNwJM3Co4zPQInRLBinFoO5hPPmn3gXVk66yXyRt0D7C3azQN1oArf5aO2H7Z

-- Dumped from database version 15.15
-- Dumped by pg_dump version 15.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_otp; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.accounts_otp (
    id bigint NOT NULL,
    email character varying(254) NOT NULL,
    otp_code character varying(6) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.accounts_otp OWNER TO onlineshop;

--
-- Name: accounts_otp_id_seq; Type: SEQUENCE; Schema: public; Owner: onlineshop
--

ALTER TABLE public.accounts_otp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_otp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    user_type character varying(20) NOT NULL,
    email character varying(254),
    first_name character varying(30) NOT NULL,
    last_name character varying(30) NOT NULL,
    birth_date date,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.accounts_user OWNER TO onlineshop;

--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_user_groups OWNER TO onlineshop;

--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: onlineshop
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: onlineshop
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_user_user_permissions OWNER TO onlineshop;

--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: onlineshop
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: addresses_address; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.addresses_address (
    id bigint NOT NULL,
    city character varying(100) NOT NULL,
    street character varying(255) NOT NULL,
    state character varying(100) NOT NULL,
    postal_code character varying(20) NOT NULL,
    country character varying(100) NOT NULL,
    is_default boolean NOT NULL,
    user_id bigint NOT NULL,
    phone_number character varying(13) NOT NULL
);


ALTER TABLE public.addresses_address OWNER TO onlineshop;

--
-- Name: addresses_address_id_seq; Type: SEQUENCE; Schema: public; Owner: onlineshop
--

ALTER TABLE public.addresses_address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.addresses_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO onlineshop;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: onlineshop
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO onlineshop;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: onlineshop
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO onlineshop;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: onlineshop
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carts_cart; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.carts_cart (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    discount_code_id bigint,
    user_id bigint,
    session_key character varying(40),
    updated_at timestamp with time zone NOT NULL,
    discount_percent numeric(5,2) NOT NULL
);


ALTER TABLE public.carts_cart OWNER TO onlineshop;

--
-- Name: carts_cart_id_seq; Type: SEQUENCE; Schema: public; Owner: onlineshop
--

ALTER TABLE public.carts_cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carts_cartitem; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.carts_cartitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    cart_id bigint NOT NULL,
    product_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT carts_cartitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.carts_cartitem OWNER TO onlineshop;

--
-- Name: carts_cartitem_id_seq; Type: SEQUENCE; Schema: public; Owner: onlineshop
--

ALTER TABLE public.carts_cartitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_cartitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO onlineshop;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: onlineshop
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO onlineshop;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: onlineshop
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO onlineshop;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: onlineshop
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO onlineshop;

--
-- Name: orders_discountcode; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.orders_discountcode (
    id bigint NOT NULL,
    code character varying(50) NOT NULL,
    discount_percent integer NOT NULL
);


ALTER TABLE public.orders_discountcode OWNER TO onlineshop;

--
-- Name: orders_discountcode_id_seq; Type: SEQUENCE; Schema: public; Owner: onlineshop
--

ALTER TABLE public.orders_discountcode ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_discountcode_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_order; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.orders_order (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    status character varying(20) NOT NULL,
    total_price numeric(10,2) NOT NULL,
    discount_code_id bigint,
    user_id bigint NOT NULL,
    payment_status character varying(20) NOT NULL,
    shipping_city character varying(100),
    shipping_country character varying(100) NOT NULL,
    shipping_phone_number character varying(13),
    shipping_postal_code character varying(20),
    shipping_state character varying(100),
    shipping_street character varying(255)
);


ALTER TABLE public.orders_order OWNER TO onlineshop;

--
-- Name: orders_order_id_seq; Type: SEQUENCE; Schema: public; Owner: onlineshop
--

ALTER TABLE public.orders_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_orderitem; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.orders_orderitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    price_at_purchase numeric(10,2) NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT orders_orderitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.orders_orderitem OWNER TO onlineshop;

--
-- Name: orders_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: onlineshop
--

ALTER TABLE public.orders_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_brand; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.products_brand (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    website character varying(200)
);


ALTER TABLE public.products_brand OWNER TO onlineshop;

--
-- Name: products_brand_id_seq; Type: SEQUENCE; Schema: public; Owner: onlineshop
--

ALTER TABLE public.products_brand ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_brand_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_category; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.products_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    parent_id bigint,
    image character varying(100)
);


ALTER TABLE public.products_category OWNER TO onlineshop;

--
-- Name: products_category_id_seq; Type: SEQUENCE; Schema: public; Owner: onlineshop
--

ALTER TABLE public.products_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_comment; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.products_comment (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    author_id bigint NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.products_comment OWNER TO onlineshop;

--
-- Name: products_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: onlineshop
--

ALTER TABLE public.products_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_product; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.products_product (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    price numeric(10,2) NOT NULL,
    discount_percent integer NOT NULL,
    details text,
    quantity integer NOT NULL,
    discounted_price numeric(10,2),
    category_id bigint NOT NULL,
    brand_id bigint,
    banner_image character varying(100)
);


ALTER TABLE public.products_product OWNER TO onlineshop;

--
-- Name: products_product_id_seq; Type: SEQUENCE; Schema: public; Owner: onlineshop
--

ALTER TABLE public.products_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_productimage; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.products_productimage (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.products_productimage OWNER TO onlineshop;

--
-- Name: products_productimage_id_seq; Type: SEQUENCE; Schema: public; Owner: onlineshop
--

ALTER TABLE public.products_productimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_productimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_rating; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.products_rating (
    id bigint NOT NULL,
    value smallint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT products_rating_value_check CHECK ((value >= 0))
);


ALTER TABLE public.products_rating OWNER TO onlineshop;

--
-- Name: products_rating_id_seq; Type: SEQUENCE; Schema: public; Owner: onlineshop
--

ALTER TABLE public.products_rating ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_rating_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wishlists_wishlist; Type: TABLE; Schema: public; Owner: onlineshop
--

CREATE TABLE public.wishlists_wishlist (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.wishlists_wishlist OWNER TO onlineshop;

--
-- Name: wishlists_wishlist_id_seq; Type: SEQUENCE; Schema: public; Owner: onlineshop
--

ALTER TABLE public.wishlists_wishlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wishlists_wishlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts_otp; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.accounts_otp (id, email, otp_code, created_at) FROM stdin;
\.


--
-- Data for Name: accounts_user; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.accounts_user (id, password, last_login, is_superuser, username, user_type, email, first_name, last_name, birth_date, is_active, is_staff, date_joined) FROM stdin;
1	pbkdf2_sha256$600000$bk0fKrcu08WIMQ14BGQnml$DQ/fO4TuiLq7uz/N8FKGe29/HVZ/xuip888EOC5Z2BM=	2025-12-20 11:40:39.055386+00	t	admin	manager	\N			\N	t	t	2025-12-20 11:40:35.004727+00
2	pbkdf2_sha256$600000$zFwH26h1mXdosQGPXDNjYo$BC1FL9Op1tN2+FfjExJJr2wNUUV0QVxcWyh0UQcechs=	\N	f	rezaya	customer	yadegarireza50@gmail.com	reza	yadegari	1992-09-23	t	f	2025-12-20 12:15:14.323299+00
\.


--
-- Data for Name: accounts_user_groups; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.accounts_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: accounts_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.accounts_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: addresses_address; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.addresses_address (id, city, street, state, postal_code, country, is_default, user_id, phone_number) FROM stdin;
2	تهران	سازمان برنامه جنوبی	تهران	8186613362	Iran	f	2	09124360055
1	aaaaa	خیابان آتشگاه کوچه 41 جنب فروشگاه پگاه بن بست سنبل پلاک 39	اصفهان	8186613361	Iran	t	2	
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add otp	6	add_otp
22	Can change otp	6	change_otp
23	Can delete otp	6	delete_otp
24	Can view otp	6	view_otp
25	Can add user	7	add_user
26	Can change user	7	change_user
27	Can delete user	7	delete_user
28	Can view user	7	view_user
29	Can add category	8	add_category
30	Can change category	8	change_category
31	Can delete category	8	delete_category
32	Can view category	8	view_category
33	Can add product	9	add_product
34	Can change product	9	change_product
35	Can delete product	9	delete_product
36	Can view product	9	view_product
37	Can add product image	10	add_productimage
38	Can change product image	10	change_productimage
39	Can delete product image	10	delete_productimage
40	Can view product image	10	view_productimage
41	Can add comment	11	add_comment
42	Can change comment	11	change_comment
43	Can delete comment	11	delete_comment
44	Can view comment	11	view_comment
45	Can add brand	12	add_brand
46	Can change brand	12	change_brand
47	Can delete brand	12	delete_brand
48	Can view brand	12	view_brand
49	Can add rating	13	add_rating
50	Can change rating	13	change_rating
51	Can delete rating	13	delete_rating
52	Can view rating	13	view_rating
53	Can add discount code	14	add_discountcode
54	Can change discount code	14	change_discountcode
55	Can delete discount code	14	delete_discountcode
56	Can view discount code	14	view_discountcode
57	Can add order	15	add_order
58	Can change order	15	change_order
59	Can delete order	15	delete_order
60	Can view order	15	view_order
61	Can add order item	16	add_orderitem
62	Can change order item	16	change_orderitem
63	Can delete order item	16	delete_orderitem
64	Can view order item	16	view_orderitem
65	Can add address	17	add_address
66	Can change address	17	change_address
67	Can delete address	17	delete_address
68	Can view address	17	view_address
69	Can add cart	18	add_cart
70	Can change cart	18	change_cart
71	Can delete cart	18	delete_cart
72	Can view cart	18	view_cart
73	Can add cart item	19	add_cartitem
74	Can change cart item	19	change_cartitem
75	Can delete cart item	19	delete_cartitem
76	Can view cart item	19	view_cartitem
77	Can add Wishlist	20	add_wishlist
78	Can change Wishlist	20	change_wishlist
79	Can delete Wishlist	20	delete_wishlist
80	Can view Wishlist	20	view_wishlist
\.


--
-- Data for Name: carts_cart; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.carts_cart (id, created_at, discount_code_id, user_id, session_key, updated_at, discount_percent) FROM stdin;
1	2025-12-20 12:15:17.046125+00	\N	2	\N	2025-12-21 10:16:47.48757+00	0.00
\.


--
-- Data for Name: carts_cartitem; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.carts_cartitem (id, quantity, cart_id, product_id, created_at, updated_at) FROM stdin;
150	1	1	14	2025-12-21 10:40:05.806627+00	2025-12-21 10:40:05.806655+00
151	1	1	18	2025-12-21 10:40:50.420237+00	2025-12-21 10:40:50.420255+00
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-12-20 11:48:51.538852+00	3	Samsung Galaxy S24 Ultra	2	[{"added": {"name": "product image", "object": "Image for Samsung Galaxy S24 Ultra"}}, {"added": {"name": "product image", "object": "Image for Samsung Galaxy S24 Ultra"}}]	9	1
2	2025-12-20 11:51:19.915036+00	17	Nike Pro Leggings	2	[{"added": {"name": "product image", "object": "Image for Nike Pro Leggings"}}]	9	1
3	2025-12-20 11:51:49.50623+00	16	Adidas Essentials Hoodie	2	[{"added": {"name": "product image", "object": "Image for Adidas Essentials Hoodie"}}]	9	1
4	2025-12-20 11:52:25.652985+00	15	Adidas Ultraboost 23	2	[{"added": {"name": "product image", "object": "Image for Adidas Ultraboost 23"}}]	9	1
5	2025-12-20 11:53:03.365235+00	14	Nike Dri-FIT Running Shorts	2	[{"added": {"name": "product image", "object": "Image for Nike Dri-FIT Running Shorts"}}]	9	1
6	2025-12-20 11:53:35.603353+00	13	Nike Air Max 90	2	[{"added": {"name": "product image", "object": "Image for Nike Air Max 90"}}]	9	1
7	2025-12-20 11:55:00.958241+00	12	Samsung Galaxy Tab S9	2	[{"added": {"name": "product image", "object": "Image for Samsung Galaxy Tab S9"}}, {"added": {"name": "product image", "object": "Image for Samsung Galaxy Tab S9"}}]	9	1
8	2025-12-20 11:55:44.692973+00	11	iPad Air	2	[{"added": {"name": "product image", "object": "Image for iPad Air"}}]	9	1
9	2025-12-20 11:56:40.408623+00	10	iPad Pro 12.9-inch	2	[{"added": {"name": "product image", "object": "Image for iPad Pro 12.9-inch"}}, {"added": {"name": "product image", "object": "Image for iPad Pro 12.9-inch"}}]	9	1
10	2025-12-20 11:57:12.532226+00	9	Lenovo ThinkPad X1 Carbon	2	[{"added": {"name": "product image", "object": "Image for Lenovo ThinkPad X1 Carbon"}}]	9	1
11	2025-12-20 11:58:20.758001+00	8	HP Spectre x360	2	[{"added": {"name": "product image", "object": "Image for HP Spectre x360"}}, {"added": {"name": "product image", "object": "Image for HP Spectre x360"}}]	9	1
12	2025-12-20 11:59:46.635338+00	7	Dell XPS 15	2	[{"added": {"name": "product image", "object": "Image for Dell XPS 15"}}]	9	1
13	2025-12-20 11:59:58.396676+00	6	MacBook Air 13-inch M2	2	[{"added": {"name": "product image", "object": "Image for MacBook Air 13-inch M2"}}]	9	1
14	2025-12-20 12:01:23.965917+00	5	MacBook Pro 16-inch M3	2	[{"added": {"name": "product image", "object": "Image for MacBook Pro 16-inch M3"}}]	9	1
15	2025-12-20 12:02:39.474866+00	4	Samsung Galaxy A54	2	[{"added": {"name": "product image", "object": "Image for Samsung Galaxy A54"}}]	9	1
16	2025-12-20 12:03:36.283531+00	2	iPhone 14	2	[{"added": {"name": "product image", "object": "Image for iPhone 14"}}]	9	1
17	2025-12-20 12:04:22.896245+00	1	iPhone 15 Pro Max	2	[{"added": {"name": "product image", "object": "Image for iPhone 15 Pro Max"}}, {"added": {"name": "product image", "object": "Image for iPhone 15 Pro Max"}}]	9	1
18	2025-12-20 12:54:26.937911+00	2	Order 2 - rezaya	2	[{"changed": {"fields": ["Status", "Payment Status"]}}]	15	1
19	2025-12-20 12:55:05.035611+00	2	Order 2 - rezaya	2	[]	15	1
20	2025-12-20 13:01:28.04052+00	1	reza - 20% Off	1	[{"added": {}}]	14	1
21	2025-12-20 13:27:20.852702+00	1	reza - 50% Off	2	[{"changed": {"fields": ["Discount percent"]}}]	14	1
22	2025-12-21 08:02:05.715373+00	17	Nike Pro Leggings	2	[{"changed": {"fields": ["Banner image"]}}]	9	1
23	2025-12-21 08:36:39.232224+00	1	iPhone 15 Pro Max	2	[{"changed": {"fields": ["Banner image"]}}]	9	1
56	2025-12-21 08:47:45.780453+00	5	MacBook Pro 16-inch M3	2	[]	9	1
57	2025-12-21 08:47:55.72784+00	1	iPhone 15 Pro Max	2	[{"changed": {"fields": ["Banner image"]}}]	9	1
58	2025-12-21 08:49:15.38963+00	1	iPhone 15 Pro Max	2	[{"changed": {"fields": ["Banner image"]}}]	9	1
59	2025-12-21 08:50:30.525444+00	1	iPhone 15 Pro Max	2	[{"changed": {"fields": ["Banner image"]}}]	9	1
60	2025-12-21 08:51:24.261096+00	8	Hermes	1	[{"added": {}}]	12	1
61	2025-12-21 08:51:45.547472+00	9	Beauty	1	[{"added": {}}]	8	1
62	2025-12-21 08:51:56.100802+00	10	Beauty → Perfum	1	[{"added": {}}]	8	1
63	2025-12-21 08:55:19.939039+00	18	terre d'hermes	1	[{"added": {}}, {"added": {"name": "product image", "object": "Image for terre d'hermes"}}]	9	1
64	2025-12-21 09:05:56.352255+00	1	Electronics	2	[{"changed": {"fields": ["Image"]}}]	8	1
65	2025-12-21 09:07:51.038112+00	5	Clothing	2	[{"changed": {"fields": ["Image"]}}]	8	1
66	2025-12-21 09:11:32.124911+00	9	Beauty	2	[{"changed": {"fields": ["Image"]}}]	8	1
67	2025-12-21 09:21:10.667239+00	8	Home & Kitchen	2	[{"changed": {"fields": ["Image"]}}]	8	1
68	2025-12-21 09:23:11.422426+00	8	Home & Kitchen	2	[{"changed": {"fields": ["Image"]}}]	8	1
69	2025-12-21 09:24:05.746808+00	8	Home & Kitchen	2	[{"changed": {"fields": ["Image"]}}]	8	1
70	2025-12-21 09:24:31.137893+00	8	Home & Kitchen	2	[]	8	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	accounts	otp
7	accounts	user
8	products	category
9	products	product
10	products	productimage
11	products	comment
12	products	brand
13	products	rating
14	orders	discountcode
15	orders	order
16	orders	orderitem
17	addresses	address
18	carts	cart
19	carts	cartitem
20	wishlists	wishlist
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-12-20 11:37:12.632528+00
2	contenttypes	0002_remove_content_type_name	2025-12-20 11:37:12.642067+00
3	auth	0001_initial	2025-12-20 11:37:12.675262+00
4	auth	0002_alter_permission_name_max_length	2025-12-20 11:37:12.679791+00
5	auth	0003_alter_user_email_max_length	2025-12-20 11:37:12.683846+00
6	auth	0004_alter_user_username_opts	2025-12-20 11:37:12.687918+00
7	auth	0005_alter_user_last_login_null	2025-12-20 11:37:12.692128+00
8	auth	0006_require_contenttypes_0002	2025-12-20 11:37:12.694154+00
9	auth	0007_alter_validators_add_error_messages	2025-12-20 11:37:12.697884+00
10	auth	0008_alter_user_username_max_length	2025-12-20 11:37:12.703593+00
11	auth	0009_alter_user_last_name_max_length	2025-12-20 11:37:12.70877+00
12	auth	0010_alter_group_name_max_length	2025-12-20 11:37:12.713415+00
13	auth	0011_update_proxy_permissions	2025-12-20 11:37:12.717238+00
14	auth	0012_alter_user_first_name_max_length	2025-12-20 11:37:12.721151+00
15	accounts	0001_initial	2025-12-20 11:37:12.757804+00
16	addresses	0001_initial	2025-12-20 11:37:12.775914+00
17	addresses	0002_alter_address_user	2025-12-20 11:37:12.785893+00
18	addresses	0003_address_phone_number	2025-12-20 11:37:12.804368+00
19	addresses	0004_alter_address_options	2025-12-20 11:37:12.814413+00
20	admin	0001_initial	2025-12-20 11:37:12.840446+00
21	admin	0002_logentry_remove_auto_add	2025-12-20 11:37:12.874378+00
22	admin	0003_logentry_add_action_flag_choices	2025-12-20 11:37:12.882149+00
23	products	0001_initial	2025-12-20 11:37:12.939307+00
24	products	0002_category_parent	2025-12-20 11:37:12.961214+00
25	products	0003_brand_product_brand	2025-12-20 11:37:12.98921+00
26	products	0004_remove_brand_logo	2025-12-20 11:37:13.001044+00
27	products	0005_remove_product_rating_rating	2025-12-20 11:37:13.028869+00
28	products	0006_alter_product_name	2025-12-20 11:37:13.036679+00
29	orders	0001_initial	2025-12-20 11:37:13.071241+00
30	orders	0002_rename_price_orderitem_price_at_purchase	2025-12-20 11:37:13.079248+00
31	orders	0003_cart_cartitem	2025-12-20 11:37:13.10849+00
32	orders	0004_remove_cartitem_cart_remove_cartitem_product_and_more	2025-12-20 11:37:13.138572+00
33	carts	0001_initial	2025-12-20 11:37:13.171323+00
34	carts	0002_cart_session_key_cart_updated_at_cartitem_added_at_and_more	2025-12-20 11:37:13.230655+00
35	carts	0003_rename_added_at_cartitem_created_at_and_more	2025-12-20 11:37:13.263016+00
36	orders	0005_order_payment_status_order_shipping_city_and_more	2025-12-20 11:37:13.312519+00
37	sessions	0001_initial	2025-12-20 11:37:13.322231+00
38	wishlists	0001_initial	2025-12-20 12:30:13.575502+00
39	products	0007_product_banner_image	2025-12-21 08:00:11.249409+00
40	products	0008_add_image_to_category	2025-12-21 09:04:33.699241+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
ywin3nrij7s390lw8pxaxsirw9qeg9mg	.eJxVjDsOwjAQBe_iGlkO_lPS5wzW7tqLA8iR4qRC3B0ipYD2zcx7iQTbWtPWy5KmLC5iEKffDYEepe0g36HdZklzW5cJ5a7Ig3Y5zrk8r4f7d1Ch12_tPFkXo2ZdojcYdYYzsorkyGAOlosBE1gPlgx5rQDZOkBlYrGBkMX7A-l_OHg:1vWvKB:baMWhXgdB8imEfDiGPoorFUji2uLFM8drftucYjv-bI	2026-01-03 11:40:39.057253+00
mlgbwb5max8tr7e2qjzppf9hs5isbj8y	e30:1vXFrW:t6LoHyXaqDUOyBPrbozAzCufwuruh1DVJuUxRGIh76o	2026-01-04 09:36:26.189452+00
\.


--
-- Data for Name: orders_discountcode; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.orders_discountcode (id, code, discount_percent) FROM stdin;
1	reza	50
\.


--
-- Data for Name: orders_order; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.orders_order (id, created_at, status, total_price, discount_code_id, user_id, payment_status, shipping_city, shipping_country, shipping_phone_number, shipping_postal_code, shipping_state, shipping_street) FROM stdin;
1	2025-12-20 12:52:56.197696+00	pending	27.99	\N	2	pending	aaaaa	Iran		8186613361	اصفهان	خیابان آتشگاه کوچه 41 جنب فروشگاه پگاه بن بست سنبل پلاک 39
2	2025-12-20 12:54:02.861989+00	completed	1231.99	\N	2	paid	aaaaa	Iran	\N	8186613361	اصفهان	خیابان آتشگاه کوچه 41 جنب فروشگاه پگاه بن بست سنبل پلاک 39
3	2025-12-20 12:58:35.56124+00	pending	2499.99	\N	2	pending	aaaaa	Iran		8186613361	اصفهان	خیابان آتشگاه کوچه 41 جنب فروشگاه پگاه بن بست سنبل پلاک 39
4	2025-12-20 13:35:48.444052+00	pending	180.00	1	2	pending	aaaaa	Iran		8186613361	اصفهان	خیابان آتشگاه کوچه 41 جنب فروشگاه پگاه بن بست سنبل پلاک 39
37	2025-12-21 06:39:00.296412+00	pending	27.99	\N	2	pending	aaaaa	Iran		8186613361	اصفهان	خیابان آتشگاه کوچه 41 جنب فروشگاه پگاه بن بست سنبل پلاک 39
38	2025-12-21 07:06:29.481425+00	pending	19.25	1	2	pending	aaaaa	Iran		8186613361	اصفهان	خیابان آتشگاه کوچه 41 جنب فروشگاه پگاه بن بست سنبل پلاک 39
39	2025-12-21 10:16:47.431314+00	pending	457.48	\N	2	pending	تهران	Iran	09124360055	8186613362	تهران	سازمان برنامه جنوبی
\.


--
-- Data for Name: orders_orderitem; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.orders_orderitem (id, quantity, price_at_purchase, order_id, product_id) FROM stdin;
1	1	27.99	1	14
2	1	1231.99	2	8
3	1	2499.99	3	5
4	1	359.99	4	4
37	1	27.99	37	14
38	1	38.49	38	16
39	1	97.49	39	13
40	1	359.99	39	4
\.


--
-- Data for Name: products_brand; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.products_brand (id, name, website) FROM stdin;
1	Apple	https://apple.com
2	Samsung	https://samsung.com
3	Dell	https://dell.com
4	HP	https://hp.com
5	Lenovo	https://lenovo.com
6	Nike	https://nike.com
7	Adidas	https://adidas.com
8	Hermes	\N
\.


--
-- Data for Name: products_category; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.products_category (id, name, parent_id, image) FROM stdin;
2	Smartphones	1	\N
3	Laptops	1	\N
4	Tablets	1	\N
6	Men's Clothing	5	\N
7	Women's Clothing	5	\N
10	Perfum	9	\N
1	Electronics	\N	categories/360_F_364410756_Ev3WoDfNyxO9c9n4tYIsU5YBQWAP3UF8.jpg
5	Clothing	\N	categories/360_F_279102096_nY6zRr4Ux585Fk4K2p8UeMkmzJKZwTua.jpg
9	Beauty	\N	categories/super-starlet-deep-model.jpg
8	Home & Kitchen	\N	categories/istockphoto-476392316-612x612.jpg
\.


--
-- Data for Name: products_comment; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.products_comment (id, content, created_at, author_id, product_id) FROM stdin;
1	wow	2025-12-20 12:32:51.100314+00	2	13
2	i like it	2025-12-20 12:32:59.192322+00	2	13
3	nice	2025-12-20 12:34:08.887449+00	2	8
4	wow	2025-12-21 10:25:55.526692+00	2	9
5	always i want it , my most favorite perfume	2025-12-21 10:26:22.117508+00	2	18
\.


--
-- Data for Name: products_product; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.products_product (id, name, price, discount_percent, details, quantity, discounted_price, category_id, brand_id, banner_image) FROM stdin;
3	Samsung Galaxy S24 Ultra	1099.99	5	Flagship Samsung phone with S Pen, 512GB storage	75	1044.99	2	2	\N
1	iPhone 15 Pro Max	1199.99	10	Latest iPhone with A17 Pro chip, 256GB storage, Titanium design	50	1079.99	2	1	products/banners/apple_black_banner.webp
18	terre d'hermes	200.00	0	the French brand Hermes is a true symbol of luxury in the fashion world. It always offers high quality products based on precision and elegance, which is also reflected in Hermes perfumes. The beginnings of the brand go back to 1837, when Thierry Hermes opened his own store, selling high quality saddles, bridles and other riding gear.	4	200.00	10	8	products/banners/hermes_terre_d_hermes_banner.webp
15	Adidas Ultraboost 23	189.99	15	Premium running shoes with Boost cushioning	150	161.49	6	7	\N
13	Nike Air Max 90	129.99	25	Classic Nike sneakers, available in multiple sizes	199	97.49	6	6	\N
12	Samsung Galaxy Tab S9	799.99	15	Android tablet with S Pen, 256GB storage	50	679.99	4	2	\N
11	iPad Air	599.99	10	iPad Air with M1 chip, 64GB storage	80	539.99	4	1	\N
10	iPad Pro 12.9-inch	1099.99	5	iPad Pro with M2 chip, 256GB storage, Liquid Retina display	40	1044.99	4	1	\N
9	Lenovo ThinkPad X1 Carbon	1599.99	8	Business laptop with Intel i7, 16GB RAM, 512GB SSD	45	1471.99	3	5	\N
4	Samsung Galaxy A54	449.99	20	Mid-range Samsung phone with great camera, 128GB	148	359.99	2	2	\N
7	Dell XPS 15	1799.99	15	Dell XPS 15 with Intel i7, 16GB RAM, 512GB SSD, NVIDIA GPU	40	1529.99	3	3	\N
6	MacBook Air 13-inch M2	1199.99	10	Lightweight MacBook Air with M2 chip, 8GB RAM, 256GB SSD	60	1079.99	3	1	\N
2	iPhone 14	799.99	15	iPhone 14 with A15 Bionic chip, 128GB storage	100	679.99	2	1	\N
8	HP Spectre x360	1399.99	12	2-in-1 convertible laptop with Intel i7, 16GB RAM, 512GB SSD	34	1231.99	3	4	\N
14	Nike Dri-FIT Running Shorts	34.99	20	Lightweight running shorts with moisture-wicking technology	298	27.99	6	6	\N
16	Adidas Essentials Hoodie	54.99	30	Comfortable cotton hoodie, available in various colors	249	38.49	7	7	\N
17	Nike Pro Leggings	44.99	20	High-waisted leggings with compression fit	400	35.99	7	6	products/banners/nltugf-Banner_1_1320x717_crop_center.webp
5	MacBook Pro 16-inch M3	2499.99	0	MacBook Pro with M3 chip, 16GB RAM, 512GB SSD	29	2499.99	3	1	
\.


--
-- Data for Name: products_productimage; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.products_productimage (id, image, product_id) FROM stdin;
1	products/samsung24_TWM9YIB.jpg	3
2	products/sddefault_LU2i0iq.jpg	3
3	products/a8213b34da127eb4c5cc1ded8ae41c6f.jpg	17
4	products/ADIHOODIE-GREENF-1_3b513198-5049-45a8-82a8-d94c899e7527.webp	16
5	products/shoes-adidas-ultraboost-light-orange-white-ss23.jpg	15
6	products/NikeDri-fitFlexWovenShort7_34.webp	14
7	products/AIRMAX90.png	13
8	products/samsung-galaxy-tab-s9-x710-8gb-128gb-wifi-gris.jpg	12
9	products/Samsung-Galaxy-Tab-S9-Ultra-render-4-.webp	12
10	products/s-l1200.png	11
11	products/92ea5a89492a71bf195258fc38c41d5591754c52_1624801478.jpg	10
12	products/ntdUUdP9uz8rgGxoRmXh2A.jpg	10
13	products/ThinkPad-X1-Carbon-4.webp	9
14	products/042gs1P3GD5s7BjaZpL5YMm-12.webp	8
15	products/HP-Spectre-x360-14-1-of-7.jpg	8
16	products/61i263fpUbL._AC_SL1372_.jpg	7
17	products/macbook-air-og-202503_nikFPhZ.jpeg	6
18	products/mbp16-spaceblack-select-202310.jpg	5
19	products/6540d64e5641fa531bdc6ab5.webp	4
20	products/Iphone-14-colors.jpg	2
21	products/1.png	1
22	products/iphone15pro__09444.1698087100.1280.1280__84434.1698087166.1280.1280__36540.jpg	1
23	products/terre-hermes-1879.jpg	18
\.


--
-- Data for Name: products_rating; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.products_rating (id, value, created_at, product_id, user_id) FROM stdin;
2	3	2025-12-20 12:33:38.395081+00	2	2
3	5	2025-12-20 12:34:03.174716+00	8	2
4	5	2025-12-20 12:43:12.297098+00	16	2
5	5	2025-12-20 12:52:20.640438+00	5	2
1	4	2025-12-20 12:33:10.239842+00	13	2
6	5	2025-12-21 10:25:50.135741+00	9	2
7	5	2025-12-21 10:26:05.459149+00	18	2
\.


--
-- Data for Name: wishlists_wishlist; Type: TABLE DATA; Schema: public; Owner: onlineshop
--

COPY public.wishlists_wishlist (id, created_at, product_id, user_id) FROM stdin;
\.


--
-- Name: accounts_otp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: onlineshop
--

SELECT pg_catalog.setval('public.accounts_otp_id_seq', 2, true);


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: onlineshop
--

SELECT pg_catalog.setval('public.accounts_user_groups_id_seq', 1, false);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: onlineshop
--

SELECT pg_catalog.setval('public.accounts_user_id_seq', 2, true);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: onlineshop
--

SELECT pg_catalog.setval('public.accounts_user_user_permissions_id_seq', 1, false);


--
-- Name: addresses_address_id_seq; Type: SEQUENCE SET; Schema: public; Owner: onlineshop
--

SELECT pg_catalog.setval('public.addresses_address_id_seq', 2, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: onlineshop
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: onlineshop
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: onlineshop
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 80, true);


--
-- Name: carts_cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: onlineshop
--

SELECT pg_catalog.setval('public.carts_cart_id_seq', 1, true);


--
-- Name: carts_cartitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: onlineshop
--

SELECT pg_catalog.setval('public.carts_cartitem_id_seq', 182, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: onlineshop
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 70, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: onlineshop
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 20, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: onlineshop
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 40, true);


--
-- Name: orders_discountcode_id_seq; Type: SEQUENCE SET; Schema: public; Owner: onlineshop
--

SELECT pg_catalog.setval('public.orders_discountcode_id_seq', 1, true);


--
-- Name: orders_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: onlineshop
--

SELECT pg_catalog.setval('public.orders_order_id_seq', 39, true);


--
-- Name: orders_orderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: onlineshop
--

SELECT pg_catalog.setval('public.orders_orderitem_id_seq', 40, true);


--
-- Name: products_brand_id_seq; Type: SEQUENCE SET; Schema: public; Owner: onlineshop
--

SELECT pg_catalog.setval('public.products_brand_id_seq', 8, true);


--
-- Name: products_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: onlineshop
--

SELECT pg_catalog.setval('public.products_category_id_seq', 10, true);


--
-- Name: products_comment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: onlineshop
--

SELECT pg_catalog.setval('public.products_comment_id_seq', 36, true);


--
-- Name: products_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: onlineshop
--

SELECT pg_catalog.setval('public.products_product_id_seq', 18, true);


--
-- Name: products_productimage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: onlineshop
--

SELECT pg_catalog.setval('public.products_productimage_id_seq', 23, true);


--
-- Name: products_rating_id_seq; Type: SEQUENCE SET; Schema: public; Owner: onlineshop
--

SELECT pg_catalog.setval('public.products_rating_id_seq', 38, true);


--
-- Name: wishlists_wishlist_id_seq; Type: SEQUENCE SET; Schema: public; Owner: onlineshop
--

SELECT pg_catalog.setval('public.wishlists_wishlist_id_seq', 39, true);


--
-- Name: accounts_otp accounts_otp_email_otp_code_6edc56e2_uniq; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.accounts_otp
    ADD CONSTRAINT accounts_otp_email_otp_code_6edc56e2_uniq UNIQUE (email, otp_code);


--
-- Name: accounts_otp accounts_otp_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.accounts_otp
    ADD CONSTRAINT accounts_otp_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_email_key; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_email_key UNIQUE (email);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_username_key; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_username_key UNIQUE (username);


--
-- Name: addresses_address addresses_address_phone_number_key; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.addresses_address
    ADD CONSTRAINT addresses_address_phone_number_key UNIQUE (phone_number);


--
-- Name: addresses_address addresses_address_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.addresses_address
    ADD CONSTRAINT addresses_address_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: carts_cart carts_cart_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.carts_cart
    ADD CONSTRAINT carts_cart_pkey PRIMARY KEY (id);


--
-- Name: carts_cart carts_cart_user_id_session_key_4898596d_uniq; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.carts_cart
    ADD CONSTRAINT carts_cart_user_id_session_key_4898596d_uniq UNIQUE (user_id, session_key);


--
-- Name: carts_cartitem carts_cartitem_cart_id_product_id_883bacdf_uniq; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.carts_cartitem
    ADD CONSTRAINT carts_cartitem_cart_id_product_id_883bacdf_uniq UNIQUE (cart_id, product_id);


--
-- Name: carts_cartitem carts_cartitem_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.carts_cartitem
    ADD CONSTRAINT carts_cartitem_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: orders_discountcode orders_discountcode_code_key; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.orders_discountcode
    ADD CONSTRAINT orders_discountcode_code_key UNIQUE (code);


--
-- Name: orders_discountcode orders_discountcode_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.orders_discountcode
    ADD CONSTRAINT orders_discountcode_pkey PRIMARY KEY (id);


--
-- Name: orders_order orders_order_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_pkey PRIMARY KEY (id);


--
-- Name: orders_orderitem orders_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_pkey PRIMARY KEY (id);


--
-- Name: products_brand products_brand_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.products_brand
    ADD CONSTRAINT products_brand_pkey PRIMARY KEY (id);


--
-- Name: products_category products_category_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.products_category
    ADD CONSTRAINT products_category_pkey PRIMARY KEY (id);


--
-- Name: products_comment products_comment_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.products_comment
    ADD CONSTRAINT products_comment_pkey PRIMARY KEY (id);


--
-- Name: products_product products_product_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_pkey PRIMARY KEY (id);


--
-- Name: products_productimage products_productimage_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.products_productimage
    ADD CONSTRAINT products_productimage_pkey PRIMARY KEY (id);


--
-- Name: products_rating products_rating_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.products_rating
    ADD CONSTRAINT products_rating_pkey PRIMARY KEY (id);


--
-- Name: products_rating products_rating_product_id_user_id_b30b595c_uniq; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.products_rating
    ADD CONSTRAINT products_rating_product_id_user_id_b30b595c_uniq UNIQUE (product_id, user_id);


--
-- Name: wishlists_wishlist wishlists_wishlist_pkey; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.wishlists_wishlist
    ADD CONSTRAINT wishlists_wishlist_pkey PRIMARY KEY (id);


--
-- Name: wishlists_wishlist wishlists_wishlist_user_id_product_id_0e217753_uniq; Type: CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.wishlists_wishlist
    ADD CONSTRAINT wishlists_wishlist_user_id_product_id_0e217753_uniq UNIQUE (user_id, product_id);


--
-- Name: accounts_user_email_b2644a56_like; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX accounts_user_email_b2644a56_like ON public.accounts_user USING btree (email varchar_pattern_ops);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: accounts_user_username_6088629e_like; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX accounts_user_username_6088629e_like ON public.accounts_user USING btree (username varchar_pattern_ops);


--
-- Name: addresses_address_phone_number_8e22f846_like; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX addresses_address_phone_number_8e22f846_like ON public.addresses_address USING btree (phone_number varchar_pattern_ops);


--
-- Name: addresses_address_user_id_01a7dcfa; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX addresses_address_user_id_01a7dcfa ON public.addresses_address USING btree (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: carts_cart_discount_code_id_57d04adc; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX carts_cart_discount_code_id_57d04adc ON public.carts_cart USING btree (discount_code_id);


--
-- Name: carts_cart_user_id_bd0756c7; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX carts_cart_user_id_bd0756c7 ON public.carts_cart USING btree (user_id);


--
-- Name: carts_cartitem_cart_id_9cb0a756; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX carts_cartitem_cart_id_9cb0a756 ON public.carts_cartitem USING btree (cart_id);


--
-- Name: carts_cartitem_product_id_acd010e4; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX carts_cartitem_product_id_acd010e4 ON public.carts_cartitem USING btree (product_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: orders_discountcode_code_f7718993_like; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX orders_discountcode_code_f7718993_like ON public.orders_discountcode USING btree (code varchar_pattern_ops);


--
-- Name: orders_order_discount_code_id_a46806cc; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX orders_order_discount_code_id_a46806cc ON public.orders_order USING btree (discount_code_id);


--
-- Name: orders_order_user_id_e9b59eb1; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX orders_order_user_id_e9b59eb1 ON public.orders_order USING btree (user_id);


--
-- Name: orders_orderitem_order_id_fe61a34d; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX orders_orderitem_order_id_fe61a34d ON public.orders_orderitem USING btree (order_id);


--
-- Name: orders_orderitem_product_id_afe4254a; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX orders_orderitem_product_id_afe4254a ON public.orders_orderitem USING btree (product_id);


--
-- Name: products_category_parent_id_3388f6c9; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX products_category_parent_id_3388f6c9 ON public.products_category USING btree (parent_id);


--
-- Name: products_comment_author_id_c88d73d4; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX products_comment_author_id_c88d73d4 ON public.products_comment USING btree (author_id);


--
-- Name: products_comment_product_id_b55b4f01; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX products_comment_product_id_b55b4f01 ON public.products_comment USING btree (product_id);


--
-- Name: products_product_brand_id_3e2e8fd1; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX products_product_brand_id_3e2e8fd1 ON public.products_product USING btree (brand_id);


--
-- Name: products_product_category_id_9b594869; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX products_product_category_id_9b594869 ON public.products_product USING btree (category_id);


--
-- Name: products_product_name_fa23bcd2; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX products_product_name_fa23bcd2 ON public.products_product USING btree (name);


--
-- Name: products_product_name_fa23bcd2_like; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX products_product_name_fa23bcd2_like ON public.products_product USING btree (name varchar_pattern_ops);


--
-- Name: products_productimage_product_id_e747596a; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX products_productimage_product_id_e747596a ON public.products_productimage USING btree (product_id);


--
-- Name: products_rating_product_id_f60bd2d8; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX products_rating_product_id_f60bd2d8 ON public.products_rating USING btree (product_id);


--
-- Name: products_rating_user_id_f9283a7e; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX products_rating_user_id_f9283a7e ON public.products_rating USING btree (user_id);


--
-- Name: wishlists_wishlist_product_id_6eeaa549; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX wishlists_wishlist_product_id_6eeaa549 ON public.wishlists_wishlist USING btree (product_id);


--
-- Name: wishlists_wishlist_user_id_cefb1e8d; Type: INDEX; Schema: public; Owner: onlineshop
--

CREATE INDEX wishlists_wishlist_user_id_cefb1e8d ON public.wishlists_wishlist USING btree (user_id);


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: addresses_address addresses_address_user_id_01a7dcfa_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.addresses_address
    ADD CONSTRAINT addresses_address_user_id_01a7dcfa_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carts_cart carts_cart_discount_code_id_57d04adc_fk_orders_discountcode_id; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.carts_cart
    ADD CONSTRAINT carts_cart_discount_code_id_57d04adc_fk_orders_discountcode_id FOREIGN KEY (discount_code_id) REFERENCES public.orders_discountcode(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carts_cart carts_cart_user_id_bd0756c7_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.carts_cart
    ADD CONSTRAINT carts_cart_user_id_bd0756c7_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carts_cartitem carts_cartitem_cart_id_9cb0a756_fk_carts_cart_id; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.carts_cartitem
    ADD CONSTRAINT carts_cartitem_cart_id_9cb0a756_fk_carts_cart_id FOREIGN KEY (cart_id) REFERENCES public.carts_cart(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carts_cartitem carts_cartitem_product_id_acd010e4_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.carts_cartitem
    ADD CONSTRAINT carts_cartitem_product_id_acd010e4_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_order orders_order_discount_code_id_a46806cc_fk_orders_di; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_discount_code_id_a46806cc_fk_orders_di FOREIGN KEY (discount_code_id) REFERENCES public.orders_discountcode(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_order orders_order_user_id_e9b59eb1_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_user_id_e9b59eb1_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderitem orders_orderitem_order_id_fe61a34d_fk_orders_order_id; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_order_id_fe61a34d_fk_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderitem orders_orderitem_product_id_afe4254a_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_product_id_afe4254a_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_category products_category_parent_id_3388f6c9_fk_products_category_id; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.products_category
    ADD CONSTRAINT products_category_parent_id_3388f6c9_fk_products_category_id FOREIGN KEY (parent_id) REFERENCES public.products_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_comment products_comment_author_id_c88d73d4_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.products_comment
    ADD CONSTRAINT products_comment_author_id_c88d73d4_fk_accounts_user_id FOREIGN KEY (author_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_comment products_comment_product_id_b55b4f01_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.products_comment
    ADD CONSTRAINT products_comment_product_id_b55b4f01_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product products_product_brand_id_3e2e8fd1_fk_products_brand_id; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_brand_id_3e2e8fd1_fk_products_brand_id FOREIGN KEY (brand_id) REFERENCES public.products_brand(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product products_product_category_id_9b594869_fk_products_category_id; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_category_id_9b594869_fk_products_category_id FOREIGN KEY (category_id) REFERENCES public.products_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_productimage products_productimag_product_id_e747596a_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.products_productimage
    ADD CONSTRAINT products_productimag_product_id_e747596a_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_rating products_rating_product_id_f60bd2d8_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.products_rating
    ADD CONSTRAINT products_rating_product_id_f60bd2d8_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_rating products_rating_user_id_f9283a7e_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.products_rating
    ADD CONSTRAINT products_rating_user_id_f9283a7e_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wishlists_wishlist wishlists_wishlist_product_id_6eeaa549_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.wishlists_wishlist
    ADD CONSTRAINT wishlists_wishlist_product_id_6eeaa549_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wishlists_wishlist wishlists_wishlist_user_id_cefb1e8d_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: onlineshop
--

ALTER TABLE ONLY public.wishlists_wishlist
    ADD CONSTRAINT wishlists_wishlist_user_id_cefb1e8d_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict lprNwJM3Co4zPQInRLBinFoO5hPPmn3gXVk66yXyRt0D7C3azQN1oArf5aO2H7Z

