# Generated by Django 4.2 on 2025-04-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='logo',
        ),
    ]
