# Generated by Django 4.2 on 2025-03-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='otp',
            unique_together={('email', 'otp_code')},
        ),
        migrations.RemoveField(
            model_name='otp',
            name='valid_until',
        ),
    ]
