# Generated by Django 4.2 on 2025-04-09 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default=0, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن معتبر وارد کنید. مانند: 09123456789 یا +989123456789', regex='^(?:\\+98|0)9\\d{9}$')], verbose_name='شماره تلفن'),
            preserve_default=False,
        ),
    ]
